import { type HeadingConfig, type TypographyState, SYSTEM_FONTS } from "../types";

type ExportResult = {
  content: string;
  filename: string;
};

function resolveFontFamily(state: TypographyState) {
  return state.fontBucket === "google"
    ? `"${state.googleFontFamily}", sans-serif`
    : SYSTEM_FONTS[state.systemFontIdx]?.css || "system-ui, sans-serif";
}

function resolveGoogleFontImport(state: TypographyState) {
  if (state.fontBucket !== "google") return "";
  const family = state.googleFontFamily.trim().replace(/\s+/g, "+");
  return `@import url("https://fonts.googleapis.com/css2?family=${family}:wght@100..900&display=swap");`;
}

function formatFluidSize(
  size: number,
  unit: HeadingConfig["fontSizeUnit"],
  state: TypographyState,
) {
  if (!state.fluidMode) {
    return `${size}${unit}`;
  }

  const minSize = Math.max(0.1, size * 0.82);
  const maxSize = size * 1.18;
  const viewportRange = Math.max(1, state.maxViewport - state.minViewport);
  const slope = ((maxSize - minSize) / viewportRange) * 100;
  const intercept = minSize - (slope * state.minViewport) / 100;

  return `clamp(${minSize.toFixed(3)}${unit}, ${intercept.toFixed(3)}${unit} + ${slope.toFixed(3)}vw, ${maxSize.toFixed(3)}${unit})`;
}

function buildSharedTextStyle(state: TypographyState) {
  return {
    textAlign: state.textAlign,
    direction: state.direction,
    textTransform: state.textTransform,
    textDecorationLine: state.textDecoration,
    textDecorationStyle: state.textDecorationStyle,
    textDecorationColor: state.textDecorationColor,
    textDecorationThickness: `${state.textDecorationThickness}px`,
    textShadow: state.textShadowEnabled
      ? `${state.textShadowX}px ${state.textShadowY}px ${state.textShadowBlur}px ${state.textShadowColor}`
      : "none",
    wordSpacing: `${state.defaultWordSpacing}${state.defaultWordSpacingUnit}`,
    whiteSpace: state.whiteSpace,
    textOverflow: state.textOverflow,
    overflow: state.textOverflow === "ellipsis" ? "hidden" : "visible",
  };
}

export function buildTypographyExport(state: TypographyState): ExportResult {
  const name = state.downloadName || "typography";
  return {
    content: generateReactComponent(state),
    filename: `${name}.tsx`,
  };
}

function generateReactComponent(state: TypographyState): string {
  const fontFamily = resolveFontFamily(state);
  const googleFontImport = resolveGoogleFontImport(state);
  const sharedStyle = buildSharedTextStyle(state);

  return `// Typography Component - Generated by UI Foundry
import React from "react";

type TypographyVariant =
  | "h1"
  | "h2"
  | "h3"
  | "h4"
  | "h5"
  | "h6"
  | "body"
  | "lead"
  | "small"
  | "caption";

interface TypographyProps {
  variant?: TypographyVariant;
  children: React.ReactNode;
  as?: keyof JSX.IntrinsicElements;
  ariaLabel?: string;
  className?: string;
  style?: React.CSSProperties;
}

const sharedStyle: React.CSSProperties = ${JSON.stringify(sharedStyle, null, 2)};

const variantStyles: Record<TypographyVariant, React.CSSProperties> = {
${state.headings
  .map(
    (heading) => `  h${heading.level}: {
    fontSize: "${formatFluidSize(heading.fontSize, heading.fontSizeUnit, state)}",
    fontWeight: ${heading.fontWeight},
    lineHeight: ${heading.lineHeight},
    letterSpacing: "${heading.letterSpacing}${heading.letterSpacingUnit}",
    textTransform: "${heading.textTransform}",
    color: "${heading.color}",
  },`,
  )
  .join("\n")}
  body: {
    fontSize: "${state.body.fontSize}${state.body.fontSizeUnit}",
    fontWeight: ${state.body.fontWeight},
    lineHeight: ${state.body.lineHeight},
    letterSpacing: "${state.body.letterSpacing}${state.body.letterSpacingUnit}",
    color: "${state.body.color}",
  },
  lead: {
    fontSize: "${state.lead.fontSize}${state.lead.fontSizeUnit}",
    fontWeight: ${state.lead.fontWeight},
    lineHeight: ${state.lead.lineHeight},
    letterSpacing: "${state.lead.letterSpacing}${state.lead.letterSpacingUnit}",
    color: "${state.lead.color}",
  },
  small: {
    fontSize: "${state.small.fontSize}${state.small.fontSizeUnit}",
    fontWeight: ${state.small.fontWeight},
    lineHeight: ${state.small.lineHeight},
    letterSpacing: "${state.small.letterSpacing}${state.small.letterSpacingUnit}",
    color: "${state.small.color}",
  },
  caption: {
    fontSize: "${state.caption.fontSize}${state.caption.fontSizeUnit}",
    fontWeight: ${state.caption.fontWeight},
    lineHeight: ${state.caption.lineHeight},
    letterSpacing: "${state.caption.letterSpacing}${state.caption.letterSpacingUnit}",
    color: "${state.caption.color}",
  },
};

const variantElements: Record<TypographyVariant, keyof JSX.IntrinsicElements> = {
  h1: "h1",
  h2: "h2",
  h3: "h3",
  h4: "h4",
  h5: "h5",
  h6: "h6",
  body: "p",
  lead: "p",
  small: "span",
  caption: "span",
};

export function Typography({
  variant = "body",
  children,
  as,
  ariaLabel = "${state.ariaLabel}",
  className,
  style,
}: TypographyProps) {
  const Component = as || variantElements[variant];
  const baseStyle: React.CSSProperties = {
    fontFamily: "${fontFamily}",
    color: "${state.defaultTextColor}",
    ...sharedStyle,
    ...variantStyles[variant],
    ...style,
  };

  return (
    <>
      ${googleFontImport ? `<style>{\`${googleFontImport}\`}</style>` : ""}
      <Component aria-label={ariaLabel || undefined} className={className} style={baseStyle}>
        {children}
      </Component>
    </>
  );
}

export default Typography;
`;
}
